#! /bin/sh

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1
#wmname LG3D

## Current theme ---------------------------------------------#

## Bspwm colors
BSPWM_FBC='#689d6a'
BSPWM_NBC='#ebdbb2'
BSPWM_ABC='#d79921'
BSPWM_PFC='#ebdbb2'

## Bspwm appearance
BSPWM_BORDER='2'
BSPWM_GAP='10'
BSPWM_SRATIO='0.50'

## Configurations --------------------------------------------#

## Manage Monitors and Workspaces
##
## Default Setup (Set 8 workspaces on each monitor)
default_workspaces() {
	for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
		bspc monitor "$monitor" -d 1 2 3 4 5 6 7 8 9
	done
}

default_workspaces

## Apply bspwm configurations
bspc config border_width "$BSPWM_BORDER"
bspc config window_gap "$BSPWM_GAP"
bspc config split_ratio "$BSPWM_SRATIO"

bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

## Autostart -------------------------------------------------#

# Kill if already running
kill -9 polybar xsettingsd sxhkd dunst xfce4-power-manager bspc

# Lauch xsettingsd daemon
# xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! $(pidof xfce-polkit) ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

sxhkd -c "$BSPDIR"/sxhkdrc &
polybar -c "$BSPDIR"/polybar/config.ini &
#bspbar &
bspcomp &
nitrogen --restore
