#!/bin/sh

# settings for common commands
alias c="clear"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias bc="bc -ql"
alias mkd="mkdir -pv"
alias ls="exa --icons --group-directories-first"
alias locate="plocate"
alias tp="trash-put"
alias tpr="trash-restore"
alias cat='bat'
alias grep='grep --color=always'